### ISSUE TITLE
[Feature] Respect `dir` in rockspecs

### ISSUE THREAD

**Issue by vhyrro** [nvim-neorocks/rocks#147]
We currently don't respect the `dir` keyword in rockspecs, causing rocks like `lua-term` to fail. Implementing this should hopefully also revert #146 (fingers crossed).

**Comment by mrcjkb** [comment]
I think we do 

https://github.com/nvim-neorocks/rocks/blob/bfb87fdbc04e9fe0438be7c983cae921a06757ff/rocks-lib/src/build/mod.rs#L140-L145
