### ISSUE TITLE
[Suggestion]: Proper lockfiles

### ISSUE THREAD

**Issue by vhyrro** [nvim-neorocks/rocks#20]
In order to make integrations with tooling like nix possible, rocks should be capable of generating detailed lockfiles with hashes and locked versions for every transitive dependency that's installed in a given rock tree.

**Comment by vhyrro** [comment]
addendum: rock trees should also have their own internal lockfiles for full reproducibility. this also inherently allows for pinning rocks in a given tree :)

**Comment by mrcjkb** [comment]
linking #86
