### ISSUE TITLE
[Tests]: Fix build test for CI

### ISSUE THREAD

**Issue by vhyrro** [nvim-neorocks/rocks#25]
The CI currently fails since it's unable to pull down the source of lua-cjson. I don't fancy vendoring that in this repository, so unsure where to take it from here.

**Comment by mrcjkb** [comment]
Can we disable the test that depends on it in CI for now?

**Comment by mrcjkb** [comment]
I've commented out the failing tests for now.

**Comment by mrcjkb** [comment]
perhaps we can temporarily re-enable the tests so they can be run locally with a `nosandbox` feature flag.
