### ISSUE TITLE
[Bug]: Manifest loading for luajit fails

### ISSUE THREAD

**Issue by vhyrro** [nvim-neorocks/rocks#54]
Since #45 `--lua-version jit` has been permitted. However, since then, rocks attempts to grab the `manifest-jit` file from luarocks.org, which obviously doesn't exist. A unified API should be put in place (`LuaVersion::normalize()`) that coerces `LuaJIT` into `Lua51`.

**Comment by max397574** [comment]
I'd be happy to do that

**Comment by vhyrro** [comment]
Since #45 be sure to also account for `--lua-version jit52` :p

**Comment by mrcjkb** [comment]
This should be fixed by #228
